# Update these as needed
crm_host: localhost
crm_database: CRM
crm_user: root
crm_password: webdev1
  
fullfillment_host: localhost
fullfillment_database: Fullfillment
fullfillment_user: root
fullfillment_password: webdev1

cache_host: localhost
cache_port: 11211
  
routes:
  __index: BundyShoes\Controller\IndexController::index
  order: BundyShoes\Controller\OrderController::processOrder