var exports = module.exports = {};
var _ = require('lodash');

/**
 * Get geo information used in beacon
 *
 * localIP is static, and does not match actual geo, as it just appears
 * in the snapshot
 *
 * @returns {{country, region, city, localIP}}
 */
exports.getGeo = function() {
    var geos = [
        { country: 'United Kingdom', region: 'Bolton', city: 'Horwich' },
        { country: 'United Kingdom', region: 'Brighton and Hove', city: 'Brighton' },
        { country: 'United Kingdom', region: 'East Sussex', city: 'Peacehaven' },
        { country: 'United Kingdom', region: 'West Sussex', city: 'Worthing' },
        { country: 'United Kingdom', region: 'Greater London', city: 'Bromley' },
        { country: 'United Kingdom', region: 'Kent', city: 'Swanley' },
        { country: 'United Kingdom', region: 'City of Bristol', city: 'Bristol' },
        { country: 'United Kingdom', region: 'South Gloucestershire', city: 'Kingswood' },
        { country: 'United Kingdom', region: 'North Somerset', city: 'Portbury' },
        { country: 'United Kingdom', region: 'Castlereagh', city: 'Dundonald' },
        { country: 'United Kingdom', region: 'Lisburn', city: 'Dunmurry' },
        { country: 'United Kingdom', region: 'North Down', city: 'Holywood' },
        { country: 'United Kingdom', region: 'Ards', city: 'Donaghadee' },
        { country: 'United Kingdom', region: 'Down', city: 'Newcastle' },
        { country: 'United Kingdom', region: 'Newtownabbey', city: 'Whiteabbey' },
        { country: 'United Kingdom', region: 'Antrim', city: 'Mill Town' },
        { country: 'United Kingdom', region: 'Derry', city: 'Londonderry' },
        { country: 'United Kingdom', region: 'Moyle', city: 'Ballycastle' },
        { country: 'United Kingdom', region: 'Coleraine', city: 'Portstewart' },
        { country: 'United Kingdom', region: 'Craigavon', city: 'Portadown' },
        { country: 'United Kingdom', region: 'Dungannon', city: 'Fivemiletown' },
        { country: 'United Kingdom', region: 'Cumbria', city: 'Carlisle' },
        { country: 'United Kingdom', region: 'Cambridgeshire', city: 'Fulbourn' },
        { country: 'United Kingdom', region: 'Essex', city: 'Saffron Walden' },
        { country: 'United Kingdom', region: 'Suffolk', city: 'Haverhill' },
        { country: 'United Kingdom', region: 'Cardiff', city: 'Butetown' },
        { country: 'United Kingdom', region: 'Bridgend', city: 'Pencoed' },
        { country: 'United Kingdom', region: 'Rhondda Cynon Taff', city: 'Pontypridd' },
        { country: 'United Kingdom', region: 'The Vale of Glamorgan', city: 'Llantwit Major' },
        { country: 'United Kingdom', region: 'Caerphilly', city: 'Bargoed' },
        { country: 'United Kingdom', region: 'Cheshire West and Chester', city: 'Chester' },
        { country: 'United Kingdom', region: 'Flintshire', city: 'Saltney' },
        { country: 'United Kingdom', region: 'Dumfries and Galloway', city: 'Annan' },
        { country: 'United Kingdom', region: 'North East Lincolnshire', city: 'Cleethorpes' },
        { country: 'United Kingdom', region: 'City of Edinburgh', city: 'Edinburgh' },
        { country: 'United Kingdom', region: 'York', city: 'Heslington' },

        {country : 'United States', region : 'Washington', city : 'Seattle' },
        {country : 'United States', region : 'California', city : 'San Francisco' },
        {country : 'United States', region : 'Nevada', city : 'Reno' },
        {country : 'United States', region : 'Texas', city : 'Dallas' },
        {country : 'United States', region : 'Oregon', city : 'Portland' },
        {country : 'United States', region : 'Colorado', city : 'Denver' },
        {country : 'United States', region : 'Nebraska', city : 'Omaha' },
        {country : 'United States', region : 'Florida', city : 'Tampa' },
        {country : 'United States', region : 'New York', city : 'New York City' },
        {country : 'United States', region : 'Idaho', city : 'Boise' },
        {country : 'United States', region : 'Montana', city : 'Bozeman' },
        {country : 'United States', region : 'Utah', city : 'Salt Lake City' },
        {country : 'United States', region : 'New Mexico', city : 'Santa Fe' },
        {country : 'United States', region : 'Arizona', city : 'Phoenix' },
        {country : 'United States', region : 'Oklahoma', city : 'Oklahoma City' },
        {country : 'United States', region : 'Kansas', city : 'Toto' },
        {country : 'United States', region : 'Nebraska', city : 'Lincoln' },
        {country : 'United States', region : 'South Dakota', city : 'Pierre' },
        {country : 'United States', region : 'Minnesota', city : 'St. Paul' },
        {country : 'United States', region : 'Missouri', city : 'Jefferson City' },
        {country : 'United States', region : 'Arkansas', city : 'Little Rock' },
        {country : 'United States', region : 'Alabama', city : 'Montgomery' },
        {country : 'United States', region : 'Kentucky', city : 'Frankfort' },
        {country : 'United States', region : 'South Carolina', city : 'Columbia' },
        {country : 'United States', region : 'New Jersey', city : 'Trenton' },
        {country : 'United States', region : 'Maine', city : 'Augusta' },

        {country : 'France', region : 'Alsace', city : 'Strasbourg' },
        {country : 'France', region : 'Aquitaine', city : 'Bordeaux' },
        {country : 'France', region : 'Auvergne', city : 'Clermont-Ferrand' },
        {country : 'France', region : 'Bretagne', city : 'Rennes' },
        {country : 'France', region : 'Bourgogne', city : 'Dijon' },
        {country : 'France', region : 'Centre-Val de Loire', city : 'Orleans' },
        {country : 'France', region : 'Champagne-Ardenne', city : '	Chalons-en-Champagne' },
        {country : 'France', region : 'Franche-Comte', city : 'Besancon' },
        {country : 'France', region : 'Ile-de-France', city : 'Paris' },
        {country : 'France', region : 'Languedoc-Roussillon', city : 'Montpellier' },
        {country : 'France', region : 'Limousin', city : 'Limoges' },
        {country : 'France', region : 'Lorraine', city : 'Metz' },
        {country : 'France', region : 'Basse-Normandie', city : 'Caen' },
        {country : 'France', region : 'Midi-Pyrenees', city : 'Toulouse' },
        {country : 'France', region : 'Nord-Pas-de-Calais', city : 'Lille' },
        {country : 'France', region : 'Pays de la Loire', city : 'Nantes' },
        {country : 'France', region : 'Picardie', city : 'Amiens' },
        {country : 'France', region : 'Poitou-Charentes', city : 'Poitiers' },
        {country : 'France', region : 'Rhone-Alpes', city : 'Lyon' },
        {country : 'France', region : 'Haute-Normandie', city : 'Rouen' },

        {country : 'Canada', region : 'British Columbia', city : 'Vancouver' },
        {country : 'Canada', region : 'Alberta', city : 'Calgary' },
        {country : 'Canada', region : 'Yukon Territory', city : 'Whitehorse' },
        {country : 'Canada', region : 'Northwest Territory', city : 'Yellow Knife' },
        {country : 'Canada', region : 'Saskatchewan', city : 'Regina' },
        {country : 'Canada', region : 'Manitoba', city : 'Winnipeg' },
        {country : 'Canada', region : 'Ontario', city : 'Toronto' },
        {country : 'Canada', region : 'Quebec', city : 'Montreal' },
        {country : 'Canada', region : 'Newfoundland', city : 'St-Johns' },

        {country : 'Spain', region : 'Madrid', city : 'Madrid' },
        {country : 'Portugal', region : 'Lisboa', city : 'Lisbon' },
        {country : 'Germany', region : 'Hessen', city : 'Frankfurt' },
        {country : 'Italy', region : 'Toscana', city : 'Florence' },
        {country : 'Poland', region : 'Warsaw', city : 'Warsaw' },
        {country : 'Czech Republic', region : 'Prague', city : 'Prague' },
        {country : 'Greece', region : 'Athens', city : 'Athens' },
        {country : 'Romania', region : 'Bucharest', city : 'Bucharest' },
        {country : 'Ireland', region : 'Dublin', city : 'Dublin' },

        {country : 'Morocco', region : 'Fez', city : 'Fez' },
        {country : 'South Africa', region : 'Cape Town', city : 'Cape Town' },
        {country : 'Egypt', region : 'Cairo', city : 'Cairo' },

        {country : 'Mexico', region : 'Mexico City', city : 'Mexico City' },
        {country : 'Panama', region : 'Panama City', city : 'Panama City' },
        {country : 'Colombia', region : 'Cundinamarca', city : 'Bogota' },
        {country : 'Chile', region : 'Region IV', city : 'Santiago' },
        {country : 'Argentina', region : 'Buenos Aires', city : 'Buenos Aires' },
        {country : 'Peru', region : 'Lima', city : 'Lima' },

        {country : 'Brazil', region : 'Amazonas', city : 'Manaus' },
        {country : 'Brazil', region : 'Bahia', city : 'Salvador' },
        {country : 'Brazil', region : 'Mato Grosso', city : 'Cuiaba' },
        {country : 'Brazil', region : 'Rio de Janeiro', city : 'Rio de Janeiro' },
        {country : 'Brazil', region : 'Sao Paulo', city : 'Sao Paulo' },

        {country : 'Russian Federation', region : 'Kamchatka', city : 'Fedotyev' },
        {country : 'Russian Federation', region : 'Vologda', city : 'Vologda' },
        {country : 'Russian Federation', region : 'Krasnoyarsk', city : 'Krasnoyarsk' },

        {country : 'China', region : 'Hebei', city : 'Beijing' },
        {country : 'China', region : 'Yunnan', city : 'Kunming' },
        {country : 'China', region : 'Hubei', city : 'Wuhan' },

        {country : 'Japan', region : 'Hokkaido', city : 'Sapporo' },
        {country : 'Japan', region : 'Tokyo', city : 'Tokyo' },

        {country : 'India', region : 'Maharashtra', city : 'Mumbai' },
        {country : 'India', region : 'Kerala', city : 'Thiruvananthapuram' },
        {country : 'India', region : 'Rajasthan', city : 'Jaipur' },

        {country : 'Australia', region : 'Victoria', city : 'Melbourne' },
        {country : 'Australia', region : 'South Australia', city : 'Adelaide' },
        {country : 'Australia', region : 'New South Wales', city : 'Sydney' },
        {country : 'Australia', region : 'Queensland', city : 'Brisbane' },

    ];
    var geo =  geos[_.random(0, (geos.length - 1))];
    geo.localIP = "7a3717be"; //this is some random IP, does not match actual geo
    return geo;
}
