var exports = module.exports = {};
var _ = require('lodash');

/**
 * Get geo information used in beacon
 *
 * localIP is static, and does not match actual geo, as it just appears
 * in the snapshot
 *
 * @returns {{country, region, city, localIP}}
 */
exports.getGeo = function() {
    var geos = [
        { country: 'United Kingdom', region: 'Aberdeen City', city: 'Aberdeen' },
        { country: 'United Kingdom', region: 'Aberdeenshire', city: 'Laurencekirk' },
        { country: 'United Kingdom', region: 'Hertfordshire', city: 'St Albans' },
        { country: 'United Kingdom', region: 'Solihull', city: 'Castle Bromwich' },
        { country: 'United Kingdom', region: 'Birmingham', city: 'Tees Grove' },
        { country: 'United Kingdom', region: 'Sandwell', city: 'West Bromwich' },
        { country: 'United Kingdom', region: 'Warwickshire', city: 'Coleshill' },
        { country: 'United Kingdom', region: 'Worcestershire', city: 'Wythall' },
        { country: 'United Kingdom', region: 'Dudley', city: 'Hurst Green' },
        { country: 'United Kingdom', region: 'Staffordshire', city: 'Tamworth' },
        { country: 'United Kingdom', region: 'Bath and North East Somerset', city: 'Bath'},
        { country: 'United Kingdom', region: 'Somerset', city: 'Bruton' },
        { country: 'United Kingdom', region: 'Wiltshire', city: 'Longbridge Deverill' },
        { country: 'United Kingdom', region: 'Lancashire', city: 'Burnley' },
        { country: 'United Kingdom', region: 'Bradford', city: 'Queensbury' },
        { country: 'United Kingdom', region: 'Kirklees', city: 'Dewsbury' },
        { country: 'United Kingdom', region: 'North Yorkshire', city: 'Thorlby' },
        { country: 'United Kingdom', region: 'Dorset', city: 'Upton' },
        { country: 'United Kingdom', region: 'Hampshire', city: 'New Milton' },
        { country: 'United Kingdom', region: 'Bury', city: 'Ramsbottom' },
        { country: 'United Kingdom', region: 'Bolton', city: 'Horwich' },
        { country: 'United Kingdom', region: 'Brighton and Hove', city: 'Brighton' },
        { country: 'United Kingdom', region: 'East Sussex', city: 'Peacehaven' },
        { country: 'United Kingdom', region: 'West Sussex', city: 'Worthing' },
        { country: 'United Kingdom', region: 'Greater London', city: 'Bromley' },
        { country: 'United Kingdom', region: 'Kent', city: 'Swanley' },
        { country: 'United Kingdom', region: 'City of Bristol', city: 'Bristol' },
        { country: 'United Kingdom', region: 'South Gloucestershire', city: 'Kingswood' },
        { country: 'United Kingdom', region: 'North Somerset', city: 'Portbury' },
        { country: 'United Kingdom', region: 'Castlereagh', city: 'Dundonald' },
        { country: 'United Kingdom', region: 'Lisburn', city: 'Dunmurry' },
        { country: 'United Kingdom', region: 'North Down', city: 'Holywood' },
        { country: 'United Kingdom', region: 'Ards', city: 'Donaghadee' },
        { country: 'United Kingdom', region: 'Down', city: 'Newcastle' },
        { country: 'United Kingdom', region: 'Newtownabbey', city: 'Whiteabbey' },
        { country: 'United Kingdom', region: 'Antrim', city: 'Mill Town' },
        { country: 'United Kingdom', region: 'Derry', city: 'Londonderry' },
        { country: 'United Kingdom', region: 'Moyle', city: 'Ballycastle' },
        { country: 'United Kingdom', region: 'Coleraine', city: 'Portstewart' },
        { country: 'United Kingdom', region: 'Craigavon', city: 'Portadown' },
        { country: 'United Kingdom', region: 'Dungannon', city: 'Fivemiletown' },
        { country: 'United Kingdom', region: 'Cumbria', city: 'Carlisle' },
        { country: 'United Kingdom', region: 'Cambridgeshire', city: 'Fulbourn' },
        { country: 'United Kingdom', region: 'Essex', city: 'Saffron Walden' },
        { country: 'United Kingdom', region: 'Suffolk', city: 'Haverhill' },
        { country: 'United Kingdom', region: 'Cardiff', city: 'Butetown' },
        { country: 'United Kingdom', region: 'Bridgend', city: 'Pencoed' },
        { country: 'United Kingdom', region: 'Rhondda Cynon Taff', city: 'Pontypridd' },
        { country: 'United Kingdom', region: 'The Vale of Glamorgan', city: 'Llantwit Major' },
        { country: 'United Kingdom', region: 'Caerphilly', city: 'Bargoed' },
        { country: 'United Kingdom', region: 'Cheshire West and Chester', city: 'Chester' },
        { country: 'United Kingdom', region: 'Flintshire', city: 'Saltney' },
        { country: 'United Kingdom',
            region: 'Wirral',
            city: 'Birkenhead' },
        { country: 'United Kingdom',
            region: 'Surrey',
            city: 'Whyteleafe' },
        { country: 'United Kingdom',
            region: 'Leicestershire',
            city: 'Market Bosworth' },
        { country: 'United Kingdom',
            region: 'Coventry',
            city: 'Hawkes End' },
        { country: 'United Kingdom',
            region: 'Cheshire East',
            city: 'Crewe' },
        { country: 'United Kingdom',
            region: 'Dundee City',
            city: 'Dundee' },
        { country: 'United Kingdom', region: 'Angus', city: 'Kirkton' },
        { country: 'United Kingdom',
            region: 'Derbyshire',
            city: 'Swadlincote' },
        { country: 'United Kingdom',
            region: 'Dumfries and Galloway',
            city: 'Annan' },
        { country: 'United Kingdom',
            region: 'County Durham',
            city: 'Durham' },
        { country: 'United Kingdom',
            region: 'Sunderland',
            city: 'Houghton-le-Spring' },
        { country: 'United Kingdom',
            region: 'Nottinghamshire',
            city: 'Everton' },
        { country: 'United Kingdom',
            region: 'Doncaster',
            city: 'Tickhill' },
        { country: 'United Kingdom',
            region: 'East Riding of Yorkshire',
            city: 'Airmyn' },
        { country: 'United Kingdom',
            region: 'North Lincolnshire',
            city: 'Burringham' },
        { country: 'United Kingdom',
            region: 'Lincolnshire',
            city: 'Corringham' },
        { country: 'United Kingdom',
            region: 'North East Lincolnshire',
            city: 'Cleethorpes' },
        { country: 'United Kingdom',
            region: 'Shropshire',
            city: 'Cleobury Mortimer' },
        { country: 'United Kingdom',
            region: 'City of Edinburgh',
            city: 'Edinburgh' },
        { country: 'United Kingdom',
            region: 'Midlothian',
            city: 'Bonnyrigg and Lasswade' },
        { country: 'United Kingdom',
            region: 'East Lothian',
            city: 'Musselburgh' },
        { country: 'United Kingdom',
            region: 'West Lothian',
            city: 'Kirknewton' },
        { country: 'United Kingdom',
            region: 'The Scottish Borders',
            city: 'Walkerburn' },
        { country: 'United Kingdom',
            region: 'Falkirk',
            city: 'Grangepans' },
        { country: 'United Kingdom', region: 'Devon', city: 'Exeter' },
        { country: 'United Kingdom', region: 'Cornwall', city: 'Bude' },
        { country: 'United Kingdom',
            region: 'Clackmannanshire',
            city: 'Alloa' },
        { country: 'United Kingdom', region: 'Stirling', city: 'Doune' },
        { country: 'United Kingdom',
            region: 'Glasgow City',
            city: 'Glasgow' },
        { country: 'United Kingdom',
            region: 'East Renfrewshire',
            city: 'Thornliebank' },
        { country: 'United Kingdom',
            region: 'West Dunbartonshire',
            city: 'Clydebank' },
        { country: 'United Kingdom',
            region: 'East Dunbartonshire',
            city: 'Milngavie' },
        { country: 'United Kingdom',
            region: 'North Lanarkshire',
            city: 'Kilsyth' },
        { country: 'United Kingdom',
            region: 'South Lanarkshire',
            city: 'Cambuslang' },
        { country: 'United Kingdom',
            region: 'Argyll and Bute',
            city: 'Helensburgh' },
        { country: 'United Kingdom',
            region: 'Gloucestershire',
            city: 'Gloucester' },
        { country: 'United Kingdom',
            region: 'Bracknell Forest',
            city: 'Sandhurst' },
        { country: 'United Kingdom', region: 'Guernsey', city: 'ALBecq' },
        { country: 'United Kingdom',
            region: 'Calderdale',
            city: 'Halifax' },
        { country: 'United Kingdom',
            region: 'Buckinghamshire',
            city: 'Chepping Wycombe' },
        { country: 'United Kingdom',
            region: 'County of Herefordshire',
            city: 'Hampton Bishop' },
        { country: 'United Kingdom',
            region: 'Eilean Siar',
            city: 'Stornoway' },
        { country: 'United Kingdom',
            region: 'City of Kingston-upon-Hull',
            city: 'Hull' },
        { country: 'United Kingdom',
            region: ' Braddan"',
            city: '"Douglas' },
        { country: 'United Kingdom', region: 'IOM', city: 'Onchan' },
        { country: 'United Kingdom',
            region: ' Andreas"',
            city: '"St Judes' },
        { country: 'United Kingdom',
            region: 'Norfolk',
            city: 'Harleston' },
        { country: 'United Kingdom',
            region: 'Highland',
            city: 'Inverness' },
        { country: 'United Kingdom', region: 'Moray', city: 'Elgin' },
        { country: 'United Kingdom',
            region: 'North Ayrshire',
            city: 'Irvine' },
        { country: 'United Kingdom',
            region: 'East Ayrshire',
            city: 'Galston' },
        { country: 'United Kingdom',
            region: 'South Ayrshire',
            city: 'Ayr' },
        { country: 'United Kingdom',
            region: 'Orkney Islands',
            city: 'Kirkwall' },
        { country: 'United Kingdom', region: 'Fife', city: 'Kirkcaldy' },
        { country: 'United Kingdom',
            region: 'Perth and Kinross',
            city: 'Kinross' },
        { country: 'United Kingdom', region: 'Sefton', city: 'Aintree' },
        { country: 'United Kingdom',
            region: 'Liverpool',
            city: 'Garston' },
        { country: 'United Kingdom',
            region: 'Knowsley',
            city: 'Halewood' },
        { country: 'United Kingdom',
            region: 'St Helens',
            city: 'Rainhill' },
        { country: 'United Kingdom',
            region: 'Powys',
            city: 'Llandrindod Wells' },
        { country: 'United Kingdom',
            region: 'Rutland',
            city: 'Hambleton' },
        { country: 'United Kingdom',
            region: 'Northamptonshire',
            city: 'Dingley' },
        { country: 'United Kingdom',
            region: 'Wrexham',
            city: 'Broughton' },
        { country: 'United Kingdom',
            region: 'Denbighshire',
            city: 'Ruthin' },
        { country: 'United Kingdom',
            region: 'Conwy',
            city: 'Betws-yn-Rhos' },
        { country: 'United Kingdom', region: 'Gwynedd', city: 'Bala' },
        { country: 'United Kingdom',
            region: 'Isle of Anglesey',
            city: 'Beaumaris' },
        { country: 'United Kingdom', region: 'Leeds', city: 'Harewood' },
        { country: 'United Kingdom',
            region: 'Central Bedfordshire',
            city: 'Thorn' },
        { country: 'United Kingdom',
            region: 'Greater Manchester',
            city: 'Manchester' },
        { country: 'United Kingdom',
            region: 'Trafford',
            city: 'Urmston' },
        { country: 'United Kingdom',
            region: 'Rochdale',
            city: 'Middleton' },
        { country: 'United Kingdom', region: 'Salford', city: 'Walkden' },
        { country: 'United Kingdom', region: 'Wigan', city: 'Pemberton' },
        { country: 'United Kingdom',
            region: 'Tameside',
            city: 'Ashton-under-Lyne' },
        { country: 'United Kingdom',
            region: 'Medway',
            city: 'Rochester' },
        { country: 'United Kingdom',
            region: 'Milton Keynes',
            city: 'Bletchley' },
        { country: 'United Kingdom',
            region: 'Bedford Borough',
            city: 'Bedford' },
        { country: 'United Kingdom',
            region: 'Gateshead',
            city: 'Wickham and Dunston' },
        { country: 'United Kingdom',
            region: 'North Tyneside',
            city: 'Longbenton' },
        { country: 'United Kingdom',
            region: 'Newcastle Upon Tyne',
            city: 'Brunswick' },
        { country: 'United Kingdom',
            region: 'Northumberland',
            city: 'Stamfordham' },
        { country: 'United Kingdom',
            region: 'Nottingham',
            city: 'Clifton' },
        { country: 'United Kingdom', region: 'Newport', city: 'Graig' },
        { country: 'United Kingdom',
            region: 'Blaenau Gwent',
            city: 'Abertillery' },
        { country: 'United Kingdom',
            region: 'Monmouthshire',
            city: 'St Arvans' },
        { country: 'United Kingdom',
            region: 'Torfaen',
            city: 'Trevethin' },
        { country: 'United Kingdom', region: 'Oldham', city: 'Shaw' },
        { country: 'United Kingdom',
            region: 'Oxfordshire',
            city: 'Oxford' },
        { country: 'United Kingdom',
            region: 'Renfrewshire',
            city: 'Paisley' },
        { country: 'United Kingdom',
            region: 'Inverclyde',
            city: 'Wemyss Bay' },
        { country: 'United Kingdom',
            region: 'Peterborough',
            city: 'Ailsworth' },
        { country: 'United Kingdom',
            region: 'Inverness-shire',
            city: 'Isle Of Rum' },
        { country: 'United Kingdom',
            region: 'Plymouth',
            city: 'Plympton' },
        { country: 'United Kingdom',
            region: 'Isle Of Wight',
            city: 'Newport' },
        { country: 'United Kingdom',
            region: 'Pembrokeshire',
            city: 'Haverfordwest' },
        { country: 'United Kingdom',
            region: 'Swansea',
            city: 'Llansamlet' },
        { country: 'United Kingdom',
            region: 'Neath Port Talbot',
            city: 'Pontardawe' },
        { country: 'United Kingdom',
            region: 'Stockport',
            city: 'Cheadle' },
        { country: 'United Kingdom',
            region: 'Slough',
            city: 'Colnbrook with Poyle' },
        { country: 'United Kingdom',
            region: 'Windsor and Maidenhead',
            city: 'Windsor' },
        { country: 'United Kingdom',
            region: 'Swindon',
            city: 'Haydon Wick' },
        { country: 'United Kingdom',
            region: 'Southampton',
            city: '9 Arcadia Close' },
        { country: 'United Kingdom',
            region: 'Thurrock',
            city: 'Corringham' },
        { country: 'United Kingdom',
            region: 'London',
            city: 'Westminster' },
        { country: 'United Kingdom',
            region: 'Telford and Wrekin',
            city: 'St Georges and Priorslee' },
        { country: 'United Kingdom',
            region: 'Redcar and Cleveland',
            city: 'Redcar' },
        { country: 'United Kingdom',
            region: 'Walsall',
            city: 'Brownhills' },
        { country: 'United Kingdom',
            region: 'Wolverhampton',
            city: 'Wednesfield' },
        { country: 'United Kingdom', region: 'York', city: 'Heslington' },
        { country: 'United Kingdom',
            region: 'Shetland Islands',
            city: 'Sound' },

        {country : 'United States', region : 'Washington', city : 'Seattle' },
        {country : 'United States', region : 'California', city : 'San Francisco' },
        {country : 'United States', region : 'Nevada', city : 'Reno' },
        {country : 'United States', region : 'Texas', city : 'Dallas' },
        {country : 'United States', region : 'Oregon', city : 'Portland' },
        {country : 'United States', region : 'Colorado', city : 'Denver' },
        {country : 'United States', region : 'Nebraska', city : 'Omaha' },
        {country : 'United States', region : 'Florida', city : 'Tampa' },
        {country : 'United States', region : 'New York', city : 'New York City' },
        {country : 'United States', region : 'Idaho', city : 'Boise' },
        {country : 'United States', region : 'Montana', city : 'Bozeman' },
        {country : 'United States', region : 'Utah', city : 'Salt Lake City' },
        {country : 'United States', region : 'New Mexico', city : 'Santa Fe' },
        {country : 'United States', region : 'Arizona', city : 'Phoenix' },
        {country : 'United States', region : 'Oklahoma', city : 'Oklahoma City' },
        {country : 'United States', region : 'Kansas', city : 'Toto' },
        {country : 'United States', region : 'Nebraska', city : 'Lincoln' },
        {country : 'United States', region : 'South Dakota', city : 'Pierre' },
        {country : 'United States', region : 'Minnesota', city : 'St. Paul' },
        {country : 'United States', region : 'Missouri', city : 'Jefferson City' },
        {country : 'United States', region : 'Arkansas', city : 'Little Rock' },
        {country : 'United States', region : 'Alabama', city : 'Montgomery' },
        {country : 'United States', region : 'Kentucky', city : 'Frankfort' },
        {country : 'United States', region : 'South Carolina', city : 'Columbia' },
        {country : 'United States', region : 'New Jersey', city : 'Trenton' },
        {country : 'United States', region : 'Maine', city : 'Augusta' },

        {country : 'France', region : 'Alsace', city : 'Strasbourg' },
        {country : 'France', region : 'Aquitaine', city : 'Bordeaux' },
        {country : 'France', region : 'Auvergne', city : 'Clermont-Ferrand' },
        {country : 'France', region : 'Bretagne', city : 'Rennes' },
        {country : 'France', region : 'Bourgogne', city : 'Dijon' },
        {country : 'France', region : 'Centre-Val de Loire', city : 'Orleans' },
        {country : 'France', region : 'Champagne-Ardenne', city : '	Chalons-en-Champagne' },
        {country : 'France', region : 'Franche-Comte', city : 'Besançon' },
        {country : 'France', region : 'Ile-de-France', city : 'Paris' },
        {country : 'France', region : 'Languedoc-Roussillon', city : 'Montpellier' },
        {country : 'France', region : 'Limousin', city : 'Limoges' },
        {country : 'France', region : 'Lorraine', city : 'Metz' },
        {country : 'France', region : 'Basse-Normandie', city : 'Caen' },
        {country : 'France', region : 'Midi-Pyrenees', city : 'Toulouse' },
        {country : 'France', region : 'Nord-Pas-de-Calais', city : 'Lille' },
        {country : 'France', region : 'Pays de la Loire', city : 'Nantes' },
        {country : 'France', region : 'Picardie', city : 'Amiens' },
        {country : 'France', region : 'Poitou-Charentes', city : 'Poitiers' },
        {country : 'France', region : 'Rhone-Alpes', city : 'Lyon' },
        {country : 'France', region : 'Haute-Normandie', city : 'Rouen' },

        {country : 'Canada', region : 'British Columbia', city : 'Vancouver' },
        {country : 'Canada', region : 'Alberta', city : 'Calgary' },
        {country : 'Canada', region : 'Yukon Territory', city : 'Whitehorse' },
        {country : 'Canada', region : 'Northwest Territory', city : 'Yellow Knife' },
        {country : 'Canada', region : 'Saskatchewan', city : 'Regina' },
        {country : 'Canada', region : 'Manitoba', city : 'Winnipeg' },
        {country : 'Canada', region : 'Ontario', city : 'Toronto' },
        {country : 'Canada', region : 'Quebec', city : 'Montreal' },
        {country : 'Canada', region : 'Newfoundland', city : 'St-Johns' },

        {country : 'Spain', region : 'Madrid', city : 'Madrid' },
        {country : 'Portugal', region : 'Lisboa', city : 'Lisbon' },
        {country : 'Germany', region : 'Hessen', city : 'Frankfurt' },
        {country : 'Italy', region : 'Toscana', city : 'Florence' },
        {country : 'Poland', region : 'Warsaw', city : 'Warsaw' },
        {country : 'Czech Republic', region : 'Prague', city : 'Prague' },
        {country : 'Greece', region : 'Athens', city : 'Athens' },
        {country : 'Romania', region : 'Bucharest', city : 'Bucharest' },
        {country : 'Ireland', region : 'Dublin', city : 'Dublin' },

        {country : 'Morocco', region : 'Fez', city : 'Fez' },
        {country : 'South Africa', region : 'Cape Town', city : 'Cape Town' },
        {country : 'Egypt', region : 'Cairo', city : 'Cairo' },

        {country : 'Mexico', region : 'Mexico City', city : 'Mexico City' },
        {country : 'Panama', region : 'Panama City', city : 'Panama City' },
        {country : 'Colombia', region : 'Cundinamarca', city : 'Bogota' },
        {country : 'Chile', region : 'Region IV', city : 'Santiago' },
        {country : 'Argentina', region : 'Buenos Aires', city : 'Buenos Aires' },
        {country : 'Peru', region : 'Lima', city : 'Lima' },

        {country : 'Brazil', region : 'Amazonas', city : 'Manaus' },
        {country : 'Brazil', region : 'Bahia', city : 'Salvador' },
        {country : 'Brazil', region : 'Mato Grosso', city : 'Cuiaba' },
        {country : 'Brazil', region : 'Rio de Janeiro', city : 'Rio de Janeiro' },
        {country : 'Brazil', region : 'Sao Paulo', city : 'Sao Paulo' },

        {country : 'Russian Federation', region : 'Kamchatka', city : 'Fedotyev' },
        {country : 'Russian Federation', region : 'Vologda', city : 'Vologda' },
        {country : 'Russian Federation', region : 'Krasnoyarsk', city : 'Krasnoyarsk' },

        {country : 'China', region : 'Hebei', city : 'Beijing' },
        {country : 'China', region : 'Yunnan', city : 'Kunming' },
        {country : 'China', region : 'Hubei', city : 'Wuhan' },

        {country : 'Japan', region : 'Hokkaido', city : 'Sapporo' },
        {country : 'Japan', region : 'Tokyo', city : 'Tokyo' },

        {country : 'India', region : 'Maharashtra', city : 'Mumbai' },
        {country : 'India', region : 'Kerala', city : 'Thiruvananthapuram' },
        {country : 'India', region : 'Rajasthan', city : 'Jaipur' },

        {country : 'Australia', region : 'Victoria', city : 'Melbourne' },
        {country : 'Australia', region : 'South Australia', city : 'Adelaide' },
        {country : 'Australia', region : 'New South Wales', city : 'Sydney' },
        {country : 'Australia', region : 'Queensland', city : 'Brisbane' },

    ];
    var geo =  geos[_.random(0, (geos.length - 1))];
    geo.localIP = "7a3717be"; //this is some random IP, does not match actual geo
    return geo;
}